### ISSUE TITLE
Toc是怎么工作的？

### ISSUE THREAD

**Issue by KoSChicken** [dubuyuye/dubuyuye.github.io#1]
我在我的博客中用到了你的主题，非常感谢。
我想要问一下，每篇文章右侧有一个toc，但是我的博客里似乎没有起到作用，我应该做什么修改来让它生效呢？

**Comment by bit-ranger** [comment]
我跑到你的博客下看了看，发现可能是注释格式不正确，导致脚本未生效。
https://github.com/helldwellercn/helldwellercn.github.io/blob/master/res/js/post.js#L35

**Comment by KoSChicken** [comment]
问题已经解决，的确是我粗心大意把注释写错了。
