### ISSUE TITLE
哪里可以添加或删除tag？

### ISSUE THREAD

**Issue by shijunting** [dubuyuye/dubuyuye.github.io#102]
你好，我fork了你的blog，想问一下，在哪里可以改tag的种类；比如我要删除一个tag或者新增一个tag。
另外有没有实现架构的介绍，谢谢

**Comment by bit-ranger** [comment]
tags 在md的头部指定，不需要注册
例如:
https://github.com/bit-ranger/blog/blob/gh-pages/_posts/2018-03-28-large-file-diff-concurrent.md

细节可以参考
http://jekyllcn.com/docs/home/
