### ISSUE TITLE
关于 archive 中 timeline 的样式

### ISSUE THREAD

**Issue by feitian124** [dubuyuye/dubuyuye.github.io#2]
您好, 你的 jekyll 主题很喜欢, 采用了哦, 谢谢~

archive 中样式感觉排版太 "稀" 了, 即使我大屏上面看, 也一屏最多只能看到5篇文章, 不太符合 archive 的本意吧, 也不方便快速浏览. 如果能更紧凑点就好了.

**Comment by bit-ranger** [comment]
感谢支持，这个你可以自己改的，把 https://github.com/dubuyuye/blog/blob/gh-pages/static/css/archive.css#L70 设置小点就行，但是变紧凑了会有点杂乱的感觉。
