### ISSUE TITLE
swiftype problems

### ISSUE THREAD

**Issue by dschense** [dubuyuye/dubuyuye.github.io#3]
I have a small Problem with getting swiftipe running with your jekyll theme.
I created a webcrawler on my swiftype account with the domain of the site.
in the account I get 

API Key

Engine Slug

Engine Key

but nothing is working when using in 

swiftype_searchId: " "

in the _config.yml

can you help please?

**Comment by bit-ranger** [comment]
These three are not the `swiftype_searchId`.
In your engine，go to "Setup and integration"  -> "Install Search",  you could find it.

``` html
<script type="text/javascript">
...
...
  _st('install','swiftype_searchId','2.0.0');
</script>
```

In my jekyll theme, the `swiftype_searchId` will auto insert into these codes. https://github.com/dubuyuye/blog/blob/gh-pages/static/js/script.js#L51

**Comment by dschense** [comment]
THX man, its integrated now.
But there is one more  Problem. Its crawling all the time, but does not find any post or  website. 
Do i have  to set it to domain/posts or  to domain/sitemap.XML Ort just to domain? With Ort without robot.txt?

**Comment by bit-ranger** [comment]
Just set it to domain.
In your engine, go to `Manage your engine` -> `Content`, is there anything exists? If the answer is "no", try to drop this engine and recreate it.

**Comment by dschense** [comment]
Recreated the engine. After creating New with domain it tells me, that there is no sitemap.XML but in the directory there is one. 
Tried it now with ignoring this message an waiting some time.

Any hints?

**Comment by bit-ranger** [comment]
May be this issue.
https://github.com/dschense/dschense.github.io/blob/master/_config.yml#L40
the last `/` should be ignored.
In your website's `sitemap.xml` page,  these urls are illegal.
http://dschense.de/sitemap.xml
