### ISSUE TITLE
使用https

### ISSUE THREAD

**Issue by HiroaKEY** [dubuyuye/dubuyuye.github.io#5]
百度的静态资源公共库提供了https链接，例如
http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js
↓
https://openapi.baidu.com/libs/jquery/2.1.4/jquery.min.js
如果不在此使用https，新版本的firefox可能会提示加密页面含有未加密内容，并且默认不加载这些内容。

**Comment by bit-ranger** [comment]
@HiroaKEY 
已获知，非常感谢。
