### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by mastery001** [dubuyuye/dubuyuye.github.io#8]
[http://mastery001.github.io/](url)
使用您的blog，为什么页面显示却这样，在首页就会全部显示内容。
麻烦看一下，谢谢！

**Comment by bit-ranger** [comment]
我克隆了你的代码，本地运行了一下，发现一切正常。
不知你用的是什么操作系统？
默认的摘要分隔符是`\n\n`，这个在不同的系统下会有不同表现。
你可以选择在`_config.yml`中增加 `excerpt_separator: <!--more-->` 来规避此问题。

**Comment by mastery001** [comment]
我在ubuntu和mac下都是显示有问题的，按您说的在yml中加上这行配置就好使了，谢谢！
