### ISSUE TITLE
Show posts in initial page?

### ISSUE THREAD

**Issue by HenriqueCSJ** [dubuyuye/dubuyuye.github.io#9]
Hi! Your blog is, by far, the best I've seen on Jekyll. As a chemist, it is exactly what I wanted to show some papers, but I'm not experienced with Jekyll: doing some tests, I'm unable to show my recent posts on the initial page (here is a test): http://teste.mundoquimico.com.br/

How can I show my posts in the initial page (like your blog)?
Thanks in advance

**Comment by bit-ranger** [comment]
@LonelySpooky 
Thank you for your approval！
It seems like the paginate plugin does not work well.
Have you deploy your blog on github?

**Comment by HenriqueCSJ** [comment]
I'm hosting my own blog (I intend to).
I'm indeed receiving a warning:
```
[henrique@localhost MyBlog] $ jekyll serve
Ignoring sup-0.21.0 because its extensions are not built.  Try: gem pristine sup --version 0.21.0
Configuration file: /home/henrique/Web/MyBlog/_config.yml
Configuration file: /home/henrique/Web/MyBlog/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /home/henrique/Web/MyBlog
       Destination: /home/henrique/Web/MyBlog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 3.14 seconds.
 Auto-regeneration: enabled for '/home/henrique/Web/MyBlog'
Configuration file: /home/henrique/Web/MyBlog/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
Any idea on how to fix?
I'm on the last jekyll version.

**Comment by HenriqueCSJ** [comment]
Fixed by adding:
```
# Gems
gems: [jekyll-paginate]
```
to _config.xml
